This update is the full working section of jira/fortify/merge scan.
Merge request pipeline section queries scanned files for High and Crit.  If found fails pipeline.

diff --git a/DevOps/gitlab/c2sf/merge_pr/.gitlab-ci.yml b/DevOps/gitlab/c2sf/merge_pr/.gitlab-ci.yml
--- a/DevOps/gitlab/c2sf/merge_pr/.gitlab-ci.yml
+++ b/DevOps/gitlab/c2sf/merge_pr/.gitlab-ci.yml
@@ -1,37 +1,302 @@
-stages:
-  - cherry-pick
-  - merge
+# This file is a template, and might need editing before it works on your project.
+# This is a sample GitLab CI/CD configuration file that should run without any modifications.
+# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
+# it uses echo commands to simulate the pipeline execution.
+#
+# A pipeline is composed of independent jobs that run scripts, grouped into stages.
+# Stages run in sequential order, but jobs within stages run in parallel.
+#
+# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
+#
+# You can copy and paste this template into a new `.gitlab-ci.yml` file.
+# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
+#
+# To contribute improvements to CI/CD templates, please follow the Development guide at:
+# https://docs.gitlab.com/ee/development/cicd/templates.html
+# This specific template is located at:
+# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml
 
-cherry_pick_commit:
-  stage: cherry-pick
-  image: alpine/git
+stages: # List of stages for jobs, and their order of execution
+  - fortify_version_create
+  - scan
+  - jira_ticket_link_apply
+  - security
+
+variables:
+  FORTIFY_BUILD_ID: "sandbox_1"
+  GITLAB_API_TOKEN: "<your-gitlab-api-token>" # Store securely as CI/CD secret
+  FORTIFY_RESULT_FILE: fpr_report.fpr
+  FPRNAME: fpr_report.fpr
+  GITLAB_URL: "https://gitlab.c2sf.mil"
+  PROJECT_ID: "CMIS"
+  MR_IID: $CI_MERGE_REQUEST_IID
+  MR_ID: $CI_MERGE_REQUEST_ID
+
+  PRIVATE_TOKEN: "$GITLAB_API_TOKEN"
+  VERSION: $CI_COMMIT_REF_NAME
+  FF_SCRIPT_SECTIONS: "true"
+  AST_ENABLE_MR_PIPELINES: "true"
+
+fortify_version_create:
+  #image: docker-registry.c2sf.mil/ironbank/opensource/debian/debian:latest
+  image: docker-registry.c2sf.mil/cmis/rockylinux:latest
+  stage: fortify_version_create
+  before_script:
+    - mkdir -p $HOME/.docker
+    - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
+
   script:
-    - git config --global user.email "ci@example.com"
-    - git config --global user.name "CI Bot"
-    - git fetch origin
-    - git checkout $TARGET_BRANCH
-    - git cherry-pick $COMMIT_SHA
-    - git push origin HEAD:$TARGET_BRANCH
-  only:
-    - merge_requests
+    - echo "Creating OR validating version has been created"
+    # -  apk add curl jq bash
+    - export VERSION=$CI_COMMIT_REF_NAME
+    # - export VERSION="another-check15"
+    - echo $VERSION
+    - echo $CI_COMMIT_REF_NAME
+    - |
 
-create_merge_commit:
-  stage: merge
-  image: alpine/git
+      if [[ $MR_ID != "" ]]; then
+        VERSION=$MR_ID
+        fi
+
+      curl --insecure -X 'POST'  "https://fortify.c2sf.mil/api/v1/projectVersions"   -H "accept: application/json"   -H "Authorization: FortifyToken ${FORTIFY_API_TOKEN}"   -H "Content-Type: application/json"   -d '{ "name" : "'"$VERSION"'" , "active" : true, "committed": false, "project" : { "id" : "184" }, "issueTemplateId": "Prioritized-HighRisk-Project-Template" }' > version_create.json
+    - |
+      curl --insecure -X "GET" "https://fortify.c2sf.mil/api/v1/projectVersions?q=name:$VERSION&projectId=184" -H "accept: application/json" -H "Authorization: FortifyToken ${FORTIFY_API_TOKEN}" -H "Content-Type: application/json" > app.json
+    - |
+
+
+      echo "Checking version existance"
+      ls -l app.json
+      cat app.json | jq
+      # if [[ "$(cat app.json | jq .responseCode)" -ne "200" ]]; then
+      #   echo "Connection failed (HTTP $(jq -c .responseCode app.json)).  Likely network issue but check Token priv"
+      #   exit 1
+      # fi
+
+      if [[ "$(cat app.json | jq -c .responseCode)" -eq "200" ]]; then
+        echo "Connection succeeded"
+
+        if [[ $(cat app.json | jq .count) -eq "0" ]]; then
+            echo "Creating new version"
+            curl --insecure -X 'POST'   'https://fortify.c2sf.mil/api/v1/projectVersions'   -H 'accept: application/json'   -H 'Authorization: FortifyToken ${FORTIFY_API_TOKEN}'   -H 'Content-Type: application/json'   -d '{ "name" : "'"$VERSION"'" , "active" : true, "committed": false, "project" : { "id" : "184" }, "issueTemplateId": "Prioritized-HighRisk-Project-Template" }' > version_create.json
+              cat version_create.json
+
+
+            ls -l version_create.json
+        fi
+          echo "Outputing info"
+        if [[ -f version_create.json ]]; then
+
+          if [[ "$( cat version_create.json | jq -c '.responseCode' )" -eq "201" && "$( cat version_create.json | jq -c '.data.name' | tr -d '"' )" -eq $VERSION ]]; then
+            echo "Success on creation"
+            echo "Name of version:" $( jq -c ".data.name" version_create.json)
+            echo "Response code:" $( jq -c ".responseCode" version_create.json)
+            id_creation=$( jq -c ".data.name" version_create.json)
+          
+          elif [[ "$( cat version_create.json | jq -c '.responseCode' )" -eq "400" && "$( cat version_create.json | jq -c '.message' )" =~ "duplicate name" ]]; then
+            echo "Version found will use and update"
+            id_creation=$(cat app.json | jq -c '.data[]?.id' ) 
+          fi
+        fi
+      fi
+        echo "almost done"
+
+
+        
+        #  if [[ -f version_create.json ]]; then
+        #   if [[ "$( cat version_create.json | jq -c '.responseCode' )" -eq "400" && "$( cat version_create.json | jq -c '.message' )" =~ "duplicate name" ]]; then
+        #     echo "Not using version_create.json"
+        
+        #     else { id_creation=$(cat version_create.json | jq -c '.data?.id' ) }
+        #   fi
+
+          # if [[ -f app.json && $id_creation -ne "" ]]; then
+          #   id_creation=$(cat app.json | jq -c '.data?.id' )
+          # fi
+        # fi
+        echo "Committing $id_creation"
+        curl --insecure -X "PUT" "https://fortify.c2sf.mil/api/v1/projectVersions/$id_creation" -H "accept: application/json" -H "Authorization: FortifyToken ${FORTIFY_API_TOKEN}" -H "Content-Type: application/json" -d '{ "committed" : true }' | jq
+
+        exit 0
+  rules:
+    - if: '$CI_COMMIT_BRANCH == "production" || $CI_COMMIT_BRANCH == "development" || $CI_COMMIT_BRANCH == "gerrit-generated-dev"'
+      when: never # Do not run the pipeline for these branches
+    - when: always # Run the pipeline for all other branches
+
+  artifacts:
+    paths:
+      - app.json
+      - version_create.json
+
+fortify_scan: # This job runs in the build stage, which runs first.
+  image: docker-registry.c2sf.mil/factory/fortify-sca:latest
+
+  stage: scan
   script:
-    - git config --global user.email "ci@example.com"
-    - git config --global user.name "CI Bot"
-    - git fetch origin
-    - git checkout $TARGET_BRANCH
-    - git merge $SOURCE_BRANCH --no-ff -m "Merge $SOURCE_BRANCH into $TARGET_BRANCH"
-    - git push origin HEAD:$TARGET_BRANCH
-  only:
-    - merge_requests
-# api call for git commits on ticket
-# curl --fail --show-error --insecure -X GET   'https://jira.c2sf.mil/rest/gitplugin/1.0/issues/CMIS-5/commits'   -H 'accept: application/json'   -H 'Authorization: Bearer NDQ3MzI1MTQyNDQ3OkT4XjaTTxydR4566Py1lQwCl5Bs'   -H 'Content-Type: application/json'
+    - echo "Rules updates `fortifyupdate`"
+    - git config --global --add safe.directory $CI_BUILDS_DIR/$CI_PROJECT_PATH
+    - uname -a
+    # - sudo apt-get install -y ca-certificates
+    # - sudo cp local-ca.crt /usr/local/share/ca-certificates
+    # - sudo update-ca-certificates
 
-# Get all tickets with fix version
-#curl --fail --show-error --insecure -X GET   'https://jira.c2sf.mil/rest/api/2/search?jql=fixVersion="release_test1"'   -H 'accept: application/json'   -H 'Authorization: Bearer NDQ3MzI1MTQyNDQ3OkT4XjaTTxydR4566Py1lQwCl5Bs'   -H 'Content-Type: application/json'
+    - fortifyupdate
+    - echo "Analyzing all files"
+    - echo $CI_BUILDS_DIR
+    - echo "Getting files to scan"
+    - export files_to_scan=""
+    - export file_count=0
+    - file_count=(`git show --pretty="format:" --name-only`)
 
-# Sample for getting Issue info
-# curl --fail --show-error --insecure -X GET   'https://jira.c2sf.mil/rest/api/2/issue/CMIS-5'   -H 'accept: application/json'   -H 'Authorization: Bearer NDQ3MzI1MTQyNDQ3OkT4XjaTTxydR4566Py1lQwCl5Bs'   -H 'Content-Type: application/json'
+    - |
+      if [[ $CI_COMMIT_BRANCH == "production" || $CI_COMMIT_BRANCH == "development" || $CI_COMMIT_BRANCH == "gerrit-generated-dev" ]]; then
+          files_to_scan="$CI_BUILDS_DIR/$CI_PROJECT_PATH/src/htdocs/**/*"
+      else 
+        # echo "in else --"
+        echo ${#file_count[*]}
+        echo " Post file count"
+        for line in ${file_count[@]}; do
+              if [[ ${#file_count[*]} -gt "1" ]]; then 
+                files_to_scan+="$line " 
+              else
+               files_to_scan+="$line"
+              fi
+          echo $line
+            done
+      fi      
+
+      ls -l .
+
+    # - sourceanalyzer -verbose -b srcbuild $CI_BUILDS_DIR/cmis/cmis/src/htdocs/**/*
+
+    - sourceanalyzer -verbose -b srcbuild $files_to_scan
+
+    - echo "Setting FPRNAME"
+    - export FPRNAME=$(date +"%Y%m%d%H%M%S".fpr)
+    - echo "Creating FPR file"
+    - sourceanalyzer -verbose -b srcbuild -scan -f $FPRNAME
+    - echo "Deploying application to fortify"
+    - export VERSION=$CI_COMMIT_REF_NAME
+    #- export VERSION="another-check15"
+    - echo $VERSION
+    - fortifyclient -debug -url $FORTIFY_URL -authtoken $FORTIFY_TOKEN uploadFPR -file $FPRNAME -application $PROJECT -applicationVersion $VERSION
+
+  rules:
+    - if: '$CI_COMMIT_BRANCH == "production" || $CI_COMMIT_BRANCH == "development" || $CI_COMMIT_BRANCH == "gerrit-generated-dev" || $CI_PIPELINE_SOURCE == "merge_request_event"'
+      when: never # Do not run the pipeline for these branches
+    - when: always # Run the pipeline for all other branches
+
+  artifacts:
+    paths:
+      - $CI_BUILDS_DIR/$CI_PROJECT_PATH/$FPRNAME
+    expire_in: 1 week
+    # - FPRUtility -information -listIssues -categoryIssueCounts -project $FPRNAME
+    # - FPRUtility -information -listIssues -search -query "[fortify priority order]:critical || [fortify priority order]:high || [fortify priority order]:medium" -project $FPRNAME -outputFormat CSV -f vuln.csv
+
+jira_ticket_apply_fortify_url:
+  #image: docker-registry.c2sf.mil/ironbank/opensource/debian/debian:latest
+  image: docker-registry.c2sf.mil/cmis/rockylinux:latest
+  stage: jira_ticket_link_apply
+  needs:
+    - job: fortify_version_create
+      artifacts: true
+  script:
+    # - |
+    #  curl --insecure -X "GET" "https://fortify.c2sf.mil/api/v1/projectVersions?q=name:$VERSION&projectId=184" -H "accept: application/json" -H "Authorization: FortifyToken ${FORTIFY_API_TOKEN}" -H "Content-Type: application/json" > app.json
+    - |
+      if [[ -f version_create.json || -f app.json ]]; then
+          if [[ "$( cat version_create.json | jq -c '.responseCode' )" -eq "400" && "$( cat version_create.json | jq -c '.message' )" =~ "duplicate name" ]]; then
+              echo "Version found will use app.json value"
+              id_creation=$(cat app.json | jq -c '.data[].id' )
+          else {
+            id_creation=$(cat version_create.json | jq -c '.data?.id' )
+          }
+          fi
+      fi
+      echo $id_creation
+      issue_key=`echo $CI_COMMIT_MESSAGE | grep -oE '\b[C][A-Z0-9_]+-[1-9][0-9]*'`
+      ## LABEL - customfield_10272 
+      ## FORTIFY_URL - Staging is - customfield_11300
+      ##curl --fail --show-error --insecure -X PUT   'https://jira.c2sf.mil/rest/api/2/issue/CMIS-5'   -H 'accept: application/json'   -H 'Authorization: Bearer NDQ3MzI1MTQyNDQ3OkT4XjaTTxydR4566Py1lQwCl5Bs'   -H 'Content-Type: application/json' -d '{ "update": { "labels": [ { "add": "'"https://fortify.c2sf.mil/html/ssc/version/$id_creation"'" } ] } }' 
+      curl --fail --show-error --insecure -X PUT   "https://jira-opsstaging.c2sf.mil/rest/api/2/issue/$issue_key"   -H 'accept: application/json'   -H "Authorization: Bearer $JIRA_TOKEN"   -H 'Content-Type: application/json' -d '{ "fields": { "customfield_11300":"'"https://fortify.c2sf.mil/html/ssc/version/$id_creation"'"} }'
+
+      # Remove <customfield> and make customfield used for URL
+      ##curl --fail --show-error --insecure -X PUT   'https://jira.c2sf.mil/rest/api/2/issue/CMIS-5'   -H 'accept: application/json'   -H 'Authorization: Bearer NDQ3MzI1MTQyNDQ3OkT4XjaTTxydR4566Py1lQwCl5Bs'   -H 'Content-Type: application/json' -d '{ "update": { "<customfield>": [ { "set": "'"https://fortify.c2sf.mil/html/ssc/version/$id_creation"'" } ] } }'
+
+  rules:
+    - if: '$CI_COMMIT_BRANCH == "production" || $CI_COMMIT_BRANCH == "development" || $CI_COMMIT_BRANCH == "gerrit-generated-dev" || $CI_PIPELINE_SOURCE == "merge_request_event"'
+      when: never # Do not run the pipeline for these branches
+    - when: always # Run the pipeline for all other branches
+
+fortify_scan_merge_request:
+  stage: security
+  image: docker-registry.c2sf.mil/factory/fortify-sca:latest
+
+  script:
+    - echo "Getting files to scan"
+    - git config --global --add safe.directory /builds/cmis/cmis_current_clone-2026
+    - export files_to_scan=""
+    - export file_count=0
+
+    # - git config --global --add safe.directory /builds/cmis/cmis
+    - git log -6
+    - |
+      git fetch origin "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
+
+      git diff --name-only \
+        origin/"$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"...HEAD \
+        > changed_files.txt
+      cat changed_files.txt
+
+        git diff --name-only \
+        origin/"$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"...HEAD
+
+    # - file_count=(`git show --pretty="format:" --name-only $CI_MERGE_REQUEST_SOURCE_BRANCH_SHA^1..$CI_MERGE_REQUEST_TARGET_BRANCH_SHA`)
+    # - |
+    # for line in ${file_count[@]}; do
+    #         if [[ ${#file_count[*]} -gt "1" ]]; then
+    #           files_to_scan+="$line "
+    #         else
+    #          files_to_scan+="$line"
+    #         fi
+    #     echo $line
+    #       done
+    - sourceanalyzer -b srcbuild -clean
+    - sourceanalyzer -verbose -b srcbuild @changed_files.txt
+    - sourceanalyzer -b srcbuild -scan -f $CI_MERGE_REQUEST_ID.fpr
+    - |
+      FPRUtility -Xmx2G -project $CI_MERGE_REQUEST_ID.fpr -information  -search -query "[fortify priority order]:critical"
+      # BIRTReportGenerator -format html -template "CWE/SANS Top 25" -output fortify_report.html -source $CI_MERGE_REQUEST_ID.fpr
+      HIGH=$(FPRUtility -Xmx2G -project $CI_MERGE_REQUEST_ID.fpr -information  -search -query "[fortify priority order]:HIGH"| awk '{print $1}')
+      CRIT=$(FPRUtility -Xmx2G -project $CI_MERGE_REQUEST_ID.fpr -information  -search -query "[fortify priority order]:CRITICAL"| awk '{print $1}')
+
+      if [[ "$HIGH" -gt 0 ]] || [[ "$CRIT" -gt 0 ]]; then
+          echo "High/Critical vulnerabilities found"
+          echo "High" $HIGH
+          echo "Critical" $CRIT
+          exit 1
+        else  echo "No issues found";
+      fi
+
+    - echo $CI_MERGE_REQUEST_IID $CI_MERGE_REQUEST_ID
+    # - fortifyclient -debug -url $FORTIFY_URL -authtoken $FORTIFY_TOKEN uploadFPR -file $CI_MERGE_REQUEST_ID.fpr -application $PROJECT -applicationVersion $CI_MERGE_REQUEST_ID
+
+  rules:
+    - if: $CI_MERGE_REQUEST_ID
+  artifacts:
+    paths:
+      - $CI_BUILDS_DIR/$CI_PROJECT_PATH/$CI_MERGE_REQUEST_ID.fpr
+# semgrep-sast:
+#   image: docker-registry.c2sf.mil/cmis/returntocorp/semgrep:latest
+#   stage: test
+#   rules:
+#     - if: $CI_PIPELINE_SOURCE == "merge_request_event"
+#   script:
+#     - git --version
+#     - git config --global http.sslVerify false
+#     - semgrep ci --config=p/coldfusion --gitlab-sast --no-suppress-errors --debug
+
+#   artifacts:
+#     reports:
+#       sast: semgrep.sast.json
+#     when: always
+
